services:
  - type: web
    name: funpay-cardinal-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash -c 'python setup_render.py && python restart_bot.py'"
    envVars:
      - key: SESSION_SECRET
        scope: run
        sync: false
      - key: GOLDEN_KEY
        scope: run
        sync: false
      - key: TG_TOKEN
        scope: run
        sync: false
    autoDeploy: true
    repo: https://github.com/sidor0912/FunPayCardinal.git
    branch: main
